# Generated by Django 5.0.8 on 2024-08-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_centromedico_especialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponible', models.DateField(verbose_name='Fecha Disponible')),
                ('hora_disponible', models.TimeField(verbose_name='Hora Disponible')),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.centromedico')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.especialista')),
            ],
        ),
    ]
